RTCView.js

Android was crashing in the simulator (OS versions 5.1 and 6.0) and device (version 5.1.1). This fixes the simulator issue.

Fixes Android RTCVideoView.onLayout issue

---

MediaStreamEvent.js
RTCEvent.js
RTCIceCandidateEvent.js
RTCMediaStream.js
RTCPeerConnection.js
RTCPeerConnectionBase.js
package.json

Implements the `EventTarget` spec for PeerConnection and MediaStream, so that code that uses `addEventListener`/`removeEventListener` will work out of the box. With this, `peerConnection.onfoobar = handler` and `peerConnection.addEventListener('foobar', handler)` are equivalent, just like in the browser (and the spec).

Make PeerConnection and MediaStream proper EventTargets

---

RTCPeerConnection.js

fix blows up of passing `null` `streamId` instead refactored `id`

[js] fix stream id is now id instead _streamId

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

Ice servers configuration can be below codes.
```javascript
var configuration = {
"iceServers": [
{"url": "stun:stun.l.google.com:19302"},
{"urls": "stun:stun.l.google.com:19302"},
{"url": "turn:my.turn.server:3478", "username": "1461261865", "credential": "ivZhTedeY+XEMHZeB+ZayL70aoY="},
{"urls": "turn:my.turn.server:3478", "username": "1461261865", "credential": "ivZhTedeY+XEMHZeB+ZayL70aoY="},
{"urls": ["turn:my.turn.server:3478", "turn:other.turn.server:3478"], "username": "1461261865", "credential": "ivZhTedeY+XEMHZeB+ZayL70aoY="},
]
};
var pc = new RTCPeerConnection(configuration);
```

Fix TURN for Android and support both urls and url of iceServers

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

when determine `urls` key type in createIceServers(),
swich without `break` would leads to fall-through all cases.
thus crash the app due to unmatched type String and Array.

[android] fix switch syntax without break

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

1. we should check if the key exist before remove.
or it will caused 'index out of bound'
if indexOfValue returns -1 (not found)
2. accroding to:
[android document indexOfValue()](http://developer.android.com/reference/android/util/SparseArray.html#indexOfValue(E))
> Beware that this is a linear search, unlike lookups by key,
> and that multiple keys can map to the same value and this will find only one of them.
we should make sure to remove all same element mapped to different
key.
TODO: should figure a way to make both TrackID and StreamID be consistent between JS and
Native to avoid liner-search eveytime.

[android] add more checks before release

---

RTCDataChannel.js

A semicolon is required after a class property.

Missing semicolon added

---

MediaStream.js
MediaStreamError.js
MediaStreamErrorEvent.js
MediaStreamTrack.js
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

see comment in commit:
this PR:
close #51 
close #48
close #28 
1. pass correspond properties to js when create track.
2. implement track.enabled = true/false which can be used to mute a track.
3. MediaStream.removeTrack() will invoke native method now.
4. implement track.stop()
maybe unnecessary to invoke it if we explicitly release media stream.
but some implementation would use it when hangup.
this also supported in chrome and firfox.
I'm not exactly understand what this means, but here are some hints:
[Google Developers - MediaStream Deprecations](https://developers.google.com/web/updates/2015/07/mediastream-deprecations?hl=en)
[W3C track.stop() procedure](https://www.w3.org/TR/mediacapture-streams/#dom-mediastreamtrack-stop)
[W3C detached …

Complete MediaStreamTrack with Spec

---

MediaStreamTrack.js

MediaStreamTrack.js contained two identical definitions of clone.

Remove a duplicate method definition

---

RTCDataChannel.js

RTCDataChannel's readyState cannot be === 'open' and 'close' at the same time so (1) it's more efficient (when this.readyState === 'open') and (2) it better expresses reality to use an if-else-if instead of a series of ifs.

Remove an unnecessary check

---

ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m

The native counterpart of the implementation of getUserMedia in
WebRTCModule+RTCMediaStream.m initializes RTCMediaStream with 1 constant
label. That's a problem when RTCMediaStream instances gathered from
multiple getUserMedia (e.g. 1 getUserMedia for audio and 1 getUserMedia
for video)  calls are to be added to 1 RTCPeerConnection. The method
webrtc::PeerConnection::AddStream will not add (and return false for) a
MediaStreamIterface (i.e. RTCMediaStream) with a label equal to the
label of a previously added MediaStreamInterface (the function
CanAddLocalMediaStream implements the check.) Eventually, what the app
using react-native-webrtc will see is that only the first local
MediaStream is streamed to its remote peer.
The standard at https://www.w3.org/TR/mediacapture-streams/#mediastream …

Initialize RTCMediaStream with UUID

---

RTCPeerConnection.js

RTCPeerConnection's _localStreams array seems to be superfluous because local MediaStream instances get added to and removed from it but there are no get (by MediaStream id) operations. Eventually, what _localStreams achieves is keeping a reference to a MediaStream and that's unnecessary.
It's also unlikely that _localStreams will be used with get operations in the future because the standard at https://www.w3.org/TR/webrtc/#rtcpeerconnection-interface doesn't define retrieving MediaStream instances through RTCPeerConnection.

Remove an unnecessary Array of local MediaStream

---

ios/libjingle_peerconnection/Headers/RTCFileLogger.h
ios/libjingle_peerconnection/Headers/RTCLogging.h
ios/libjingle_peerconnection/Headers/RTCPeerConnection.h
ios/libjingle_peerconnection/Headers/RTCPeerConnectionInterface.h
ios/libjingle_peerconnection/libjingle_peerconnection_revision_build.txt

WebRTC lib is pre-build by [pristineio's webrtc-build-scripts](https://github.com/pristineio/webrtc-build-scripts)
This PR upgrade iOS lib to webrtc revision 11177. see: `ios/libjingle_peerconnection/libjingle_peerconnection_revision_build.txt`
**Why upgrade**
current webrtc version on iOS:
* I can run WebRTCDemo on iPhone6/iOS9 without problems.
* But I have silent voice on iPhone6/iOS9 if we relay to some TURN server. P2P is OK.
* It works on iPhone5/iOS9 for both TURN and P2P
I can't find the reason, but after I upgraded to 11177, the problems solved.

[libjingle][ios] upgrade to revision 11177

---

RTCDataChannel.js
RTCPeerConnection.js
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCDataChannel.h
ios/RCTWebRTC/WebRTCModule+RTCDataChannel.m
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

RTCDataChannel may be opened:
- either locally (which is already supported in react-native-webrtc)
using the Peer-to-peer Data API which extends the RTCPeerConnection
interface with the method createDataChannel
- or remotely (i.e. by the other peer). The local peer receives a
datachannel event through RTCPeerConnection. That's defined by the same
Peer-to-peer Data API.
In order to add support for the second scenario, remove reactTag from
DataChannel and use the streamId property of the Objective-C
RTCDataChannel as the id of the JavaScript counterpart (as done by the
browser API).

Support remotely-opened RTCDataChannel

---

MediaStream.js
MediaStreamError.js
MediaStreamErrorEvent.js
MediaStreamEvent.js
MediaStreamTrack.js
MediaStreamTrackEvent.js
MessageEvent.js
RTCDataChannel.js
RTCDataChannelEvent.js
RTCEvent.js
RTCIceCandidate.js
RTCIceCandidateEvent.js
RTCPeerConnection.js
RTCSessionDescription.js
RTCView.js
getUserMedia.js
index.js

- import statements need to be determinated by semicolons too
- if we're using ES6 imports now, we might as well use ES6 exports too
- strive to stay within 80 chars per line

Style fixes

---

android/src/main/AndroidManifest.xml

`react-native link` was failing to update the android project with the proper import class path.
This resolves the issue.

AndroidManifest.xml update - Package name fix

---

Documentation/AndroidInstallation.md

I found typo in ```AndroidInstallation.md```. This PR is fix for that.

fix typo for AndroidInstallation

---

RTCPeerConnection.js

RCTWebRTCDemo is using it, but to my surprise it was missing. Easy enough to implement though :)

Implement PeerConnection.getRemoteStreams()

---

.gitattributes

see: https://github.com/jitsi/jitsi-meet-react/commit/30a9ca40750f6a01a5eae0f8fa5c428ce541b147
> The project react-native does not provide 64-bit binaries. The project
react-native-webrtc though does provide 64-bit binaries. Unfortunately,
the app will crash at runtime on 64-bit platforms if the .apk contains
any 64-bit binaries. The solution found at
https://corbt.com/posts/2015/09/18/mixing-32-and-64bit-dependencies-in-android.html
is to explicitly exclude each 64-bit binary from during packaging.
related issue:
#131 
#111

android: disable git-lfs and remove 64-bit .so in libjingle

---

ios/RCTWebRTC/RCTConvert+WebRTC.m

It's perfectly fine to create an RTCPeerConnection without passing a configuration object (so long as you use setConfiguration() later), but native will return nil if you pass a nil configuration to the factory.

Ensure [RTCConvert RTCConfiguration:] always returns an RTCConfiguration

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

Fixes https://github.com/oney/react-native-webrtc/issues/158
And might also fix (I think this might be device specific): https://github.com/oney/react-native-webrtc/issues/116 https://github.com/oney/react-native-webrtc/issues/101

Android: Keep reference to VideoCapturers and dispose of them with media stream

---

android/src/main/java/com/oney/WebRTCModule/WebRTCView.java

Guys, do you want this? I haven't merged it myself because I'm not sure whether you'll want it. We used to get a significant amount of crash reports (in Crashlytics) related to NoSuchMethodErrors for isAttachedToWindow and isInLayout.

[Android] Fix NoSuchMethodError on API level <18

---

ios/RCTWebRTC.xcodeproj/project.pbxproj
ios/RCTWebRTC/RCTConvert+WebRTC.h
ios/RCTWebRTC/RTCVideoViewManager.h
ios/RCTWebRTC/WebRTCModule+RTCDataChannel.m
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
ios/RCTWebRTC/WebRTCModule.h
ios/RCTWebRTC/WebRTCModule.m

React-Native 0.40 introduces a breaking change and imports now require the "React/" namespace (https://github.com/facebook/react-native/releases/tag/v0.40.0).
Per the suggestion in the commit where this change was made: https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d , this PR updates imports with the "React/" namespace and updates the header include path to use `$(BUILT_PRODUCTS_DIR)/usr/local/include`. 
For my initial build following this change, I had to follow the instructions in the linked commit to add React as an explicit dependency in the scheme and disable "parallelize build". After the initial build I was able to remove the React dependency and rebuild without error.

Update imports of React headers for react-native 0.40 breaking change

---

android/src/main/java/com/oney/WebRTCModule/ReactBridgeUtil.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

GUM constraints like the following example from the readme:
```
getUserMedia({
audio: false,
video: {
optional: [{sourceId: selectedCamera.id}]
}
}
```
Are crashing on Android when attempting to get non-existent `mandatory` key from map-type constraints and attempting to get non-existent `facingMode` key for video constraints.
This PR adds `hasKey()` checks to ensure the keys exist before getting the values.

Allow for null facingMode and null constraint maps in getUserMedia (Android)

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

These are better handled by a module such as
react-native-incall-manager.
Only resetAudio() was used, which was arguably incorrect, since it's up to
the user to decide what audio mode they want for their application.

android: remove unused API methods

---

README.md

RTCMediaStream doesn't exist, fixing a typo.

MediaStream, not RTCMediaStream

---

MediaStreamTrack.js
README.md
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m

This patch adds a private custom API for switching the cameras on a
video track on the fly, without the need for add / removing tracks or
renegotiating.
It's MediaStreamTrack._switchCamera() and it only works for local video
streams, it will throw otherwise.
This is how the reference application AppRTCMobile implements camera
switching.

Add ability to switch cameras on the fly

---

ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m

By default the front camera  will be opened in 480p otherwise. This
aligns with the behavior in Android after
https://github.com/oney/react-native-webrtc/commit/f89f43c1799c2b65b99aa5d7a0114e0acf8eaf8d

ios: set default video constraints to 720p

---

ios/RCTWebRTC/RTCVideoViewManager.m
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
ios/RCTWebRTC/WebRTCModule.h
ios/RCTWebRTC/WebRTCModule.m

Will generate react tags for remote streams and tracks in the form of
{RTCPeerConnection react tag}_{stream id|track id}
This allows to receive streams/tracks with the same IDs through different PeerConnections.
Required for "peer to peer".

ios: generate reactTag for remote streams/tracks

---

android/src/main/java/com/oney/WebRTCModule/SurfaceViewRenderer.java

Port of [0] since we bundle our own SurfaceViewRenderer. It should fix
crashes on some Jelly Bean devices.
[0]:
https://chromium.googlesource.com/external/webrtc/codesearch/+/4ed5b9f62d7850fc5d9b2a006d3c368a9183c16d

android: create EGL context on render thread

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModulePackage.java

RN 0.47 removed createJSModules from ReactPackage [commit](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8)

handle RN 0.47 breaking change

---

android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
android/src/main/java/com/oney/WebRTCModule/RTCVideoViewManager.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/RTCVideoViewManager.m
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.h
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
ios/RCTWebRTC/WebRTCModule.h
ios/RCTWebRTC/WebRTCModule.m

Remote streams were leaking on Android, because when a peer connection was closed tracks were not removed from WebRTCModule. This PR stores tracks and streams in PeerConnectionObserver. Also adapts the iOS part to use similar strategy instead of special react tag syntax.

[Android] Fix leaking remote streams

---

MediaStreamTrack.js
README.md
RTCPeerConnection.js
android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
getUserMedia.js
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
withLegacyCallbacks.js

This PR adds Promise support as mentioned in #53.
- getUserMedia
- MediaStreamTrack.getSources
- createOffer
- createAnswer
- setLocalDescription
- setRemoteDescription
- addIceCandidate
- getStats
Using @philikon's idea, I defined a ``withLegacyCallbacks`` function to allow the user to choose between the callbacks and the promise version.
All the corresponding native methods now returns promises.
The README has been updated with examples using promises instead of callbacks.

Promise support

---

RTCDataChannel.js

This change ensures that if the passed TypedArray is a subview on the underlying ArrayBuffer, that we preserve the byteOffset and byteLength when converting to an Uint8Array for base64 encoding.

RTCDataChannel.send() doesn't support subarrays

---

RTCView.js
package.json

Fixes a PropTypes deprecation warning that keeps getting logged, see: https://facebook.github.io/react/warnings/dont-call-proptypes.html

Migrate to 'prop-types' module

---

android/src/main/java/com/oney/WebRTCModule/RTCVideoViewManager.java

It has a reference to the Activity, so this creates a (temporary) leak
because it keeps a reference to it until a new view is created.
Get a reference to the current context dynamically instead.

android: avoid storing a global context on RTCVideoViewManager

---

RTCPeerConnection.js
RTCUtil.js
getUserMedia.js
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m

This is a follow up of #140 and #288 and #359 
1. support constraints parsing
2. do it at JS side to reduce native code's complexity and easier to maintain / test.
original we supports `minWidth` / `minHeight` / `minFrameRate`, now add `maxXXX` for ios.
android doesn't consume `maxXXX` in current version.
I don't have any video use cases, these code is not tested / compiled.
This is meant to reduce discussion time as a demo.
@RangerMauve @ramneekhanda or any folks
please help to review / test to see if it works.
And fire a fix PR to this branch directly.
thanks!!

WIP: Video constraints (parsing in JS)

---

RTCUtil.js

This fixes an issue with getStats().
If you call getStats() with no arguments, promisify will mistakenly call getStats with the successFunction as the `track` and failureFunction as `successFunction`. By padding out the argument list this issue is avoided.

promisify: pad arguments with undefined if few are passed

---

RTCUtil.js
getUserMedia.js

I used `JSON.parse(JSON.stringify(obj))` because `Object.assign` does not clone the object deeply causing an error on the second usage of `getUserMedia` or `RTCPeerConnection.createOffer`.
Related issues: #116 #101 #104 
Cheers!

Deep clone default constraints

---

ios/RCTWebRTC/RTCVideoViewManager.m

Since RN 0.49, requiresMainQueueSetup needs to be defined if the module overrides constantsToExport.  will see the warning message when using it
For example: 
https://github.com/facebook/react-native/issues/17504
https://github.com/react-community/lottie-react-native/pull/226/files
https://github.com/react-native-community/react-native-video/pull/871/files
I saw `WebRTCModule` already have `requiresMainQueueSetup` method, so just adding the method in `RTCVideoViewManager.m` too

adding requiresMainQueueSetup method

---

android/build.gradle

fixed #522 'compile' is obsolete and has been replaced with 'implementation' and 'api'. It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

'compile' is obsolete

---

index.js

All files are using ES6 imports and exports except this one that using CommonJS `module.exports`, and in fact is mixing it with ES6 imports. This pull-request fix it having all files using ES6 imports and exports.

Use ES6 export

---

Documentation/iOSInstallation.md
README.md
package.json
react-native-webrtc.podspec

Fix #617 
- Fix links in readme to installation docs
- Fix image embeds in installation docs
- Fix other places the old `oney/react-native-webrtc` repo is referenced
[Preview of iOS Installation docs after this change](https://github.com/ruddell/react-native-webrtc/blob/fix-repo-links/Documentation/iOSInstallation.md)
We could also use relative links instead, but I don't expect the repo name will change again in the near future.

fix references to old repository location

---

RTCPeerConnection.js

This fixes #582 and allows for `pc.addIceCandidate(null)` or `pc.addIceCandidate({ candidate, sdpMid, sdpMLineIndex })` with correct values resulting in a resolved promise.

Add optional toJSON for candidate

---

README.md

Currently readme points to a repo, that has since moved to this organisation.

Update link to react-native-incall-manager

---

Documentation/iOSInstallation.md

The default react native project (created with `react-native init`) has in the generated Podfile: `platform :ios, '9.0'.
When doing `pod install` during `react-native-webrtc` installation, this gives the error:
```
[!] CocoaPods could not find compatible versions for pod "react-native-webrtc":
In Podfile:
react-native-webrtc (from `../node_modules/react-native-webrtc`)
Specs satisfying the `react-native-webrtc (from `../node_modules/react-native-webrtc`)` dependency were found, but they required a higher minimum deployment target.
```
Bumping the iOS version number to `10.0` fixes this error.

Add note about upgrading the `platform` field in Podfile

---

README.md
index.js

By calling this method the JavaScript global namespace gets "polluted" with the following additions:
* `navigator.getUserMedia()` (deprecated W3 API)
* `navigator.mediaDevices.getUserMedia()`
* `navigator.mediaDevices.enumerateDevices()`
* `window.RTCPeerConnection`
* `window.RTCIceCandidate`
* `window.RTCSessionDescription`
* `window.MediaStream`
* `window.MediaStreamTrack`
This is useful to make existing WebRTC JavaScript libraries (that expect those globals to exist) work with react-native-webrtc.
It fixes #685

Expose registerGlobals()

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m

MediaStream `addTrack` and `removeTrack` needs to include remote tracks. 
This is needed to support MediaSoup. Fixes issues #717 and #718.

MediaStream remote track support

---

RTCPeerConnection.js
ios/RCTWebRTC/WebRTCModule+RTCDataChannel.m

dataChannel.channelId is always equal to -1 while connecting. 
If create data channel with id 0 then it is not work on ios

fix: ios data channel

---

EventEmitter.js
RTCDataChannel.js
RTCPeerConnection.js
RTCView.js
ios/RCTWebRTC/WebRTCModule+RTCDataChannel.m
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
ios/RCTWebRTC/WebRTCModule+VideoTrackAdapter.m
ios/RCTWebRTC/WebRTCModule.h
ios/RCTWebRTC/WebRTCModule.m

Since `DeviceEventEmitter` is [deprecated](https://github.com/facebook/react-native/blob/1490ab12ef156bf3201882eeabfcac18a1210352/Libraries/EventEmitter/RCTNativeAppEventEmitter.js#L15), this PR switch to use `NativeEventEmitter`
Changes:
1. JS side
- replace `DeviceEventEmitter` with `NativeEventEmitter`
2. iOS native
- extends `RCTEventEmitter`
- use `sendEventWithName` from `RCTEventEmitter` to send event to JS.

Use NativeEventEmitter instead of DeviceEventEmitter

---

Documentation/AndroidInstallation.md

With autolinking, performing step 4 will result in errors as the package will be loaded twice.

Update step 4 to account for autolinking

---

ios/RCTWebRTC/VideoCaptureController.m

If the devices has been requested with the parameter `deviceId` like this `navigator.mediaDevices.getUserMedia({video: {deviceId: 'n'}})` the method `_switchCamera` will not work. Setting the `_deviceId` to `NULL` in the `switchCamera` method will allow the change.

ios: Enable camera switching

---

README.md

Spent a lot of time finding a bitcode compatible version of the WebRTC framework, mentioning it in the README, can help save others a lot of time. 😄

Add mention of how to get bitcode support

---

react-native-webrtc.podspec

According to https://github.com/facebook/react-native/issues/29633#issuecomment-694187116 - "React pod is in fact really only an umbrella dependency for pure JS applications to depend on, whereas the native APIs that these libraries rely on actually reside in the React-Core pod." and it will fail to build on Xcode12. This PR updates the dependency from `React` to `React-Core`.

fix: xcode 12 compatibility

---

Documentation/BuildingWebRTC.md
tools/build-webrtc.py

Since XCode 12 update, it look like by default warnings are treated as errors using clang.
To fix that I confirmed that adding "treat_warnings_as_errors=false" to GN_COMMON_ARGS  does fix the issue to build WebRTC from M69 to M87 for ios and android.
I also upated BuildingWebRTC.md doc to provide reference link to the WebRTC branch names.
Reference:
- https://stackoverflow.com/questions/64111205/enabling-bitcode-for-webrtc-ios
- https://bugs.chromium.org/p/webrtc/issues/detail?id=11729

Fix Build webrtc using xcode 12

---

RTCSessionDescription.js

Calling RTCSessionDescription constructor fails, if called with no argument, which is not consistent with current browser behavior.
https://github.com/react-native-webrtc/react-native-webrtc/issues/797

Added an empty object as the default parameter for RTCSessionDescription

---

README.md

The Readme still stated the current revision was 84. Its now 87

fix the "current" ver of webrtc reference to 87

---

tools/build-webrtc.py

According to webrtc source `src/build/android/envsetup.sh`, the android sdk path should be in `third_party/android_sdk/public/`, and we are using `third_party/android_tools/sdk/` currently.
Although they are almost the same, but I noticed there are some different files and different file size of the same file. 
Not sure if this is necessary

tools: change android_sdk env path

---

android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java

My team sends empty/null values in audio constraints to test device capabilities. This causes a `NullPointerException` on Android but no problems on iOS. 
This PR is checks for null values in `mandatory` audio constraints.

android: handle null values in mandatory constraints

---

ios/RCTWebRTC/WebRTCModule+RTCDataChannel.h
ios/RCTWebRTC/WebRTCModule+RTCDataChannel.m

See discussions here: https://github.com/react-native-webrtc/react-native-webrtc/issues/917
TLDR. webRTC may change passed `dataChannelId` into `potential_sid += 2`, so that in delegate methods `channelId` will be different from JS side.
I cannot compile the `ios/RCTWebRTC.xcodeproj` project. Just tested it in the other project.

Fix the logic of `dataChannelId` in iOS

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

When working on [VideoProvider](https://developer.android.com/reference/android/telecom/Connection.VideoProvider) in a new feature of [react-native-callkeep](https://github.com/react-native-webrtc/react-native-callkeep), we need to retrieve the stream of the remote video to display it in the native ongoing video call on Android.
To do so, we have to put the `getStreamForReactTag` as public to be able to retrieve the stream from `react-native-callkeep`.
I haven't found a way to do it without any change on this library, so I made this PR.

Allow to retrieve stream from outside

---

RTCPeerConnection.js
RTCSessionDescription.js
android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

Specifically here is how we are updating them now:
- localDescription:
- after calling setLocalDescription
- with any gathered ICE candidate
- when ICE gathering state transitions to completed
- remoteDescription:
- after calling setRemoteDescription
- when calling addICECandidate
Closes:
https://github.com/react-native-webrtc/react-native-webrtc/pull/787

core: update JS local/remote descriptions to match internal state

---

tools/build-webrtc.py

fix for https://github.com/react-native-webrtc/react-native-webrtc/issues/1034

build-webrtc.py: debug build almost useless without unstripped .so on Android

---

README.md
getDisplayMedia.js
index.js

This PR removes the restriction that getDisplayMedia has to send a constraints object, in the web api it is completely optional, and in this codebase it is not used anywhere. I believe removing it will make it easier not to trip over these implementation details.
Likewise, getDisplayMedia is also added in registerGlobals under navigator.mediaDevices.getDisplayMedia, as it is in the web api. No reason to register getUserMedia but not getDisplayMedia.
Readme is also updated to state that getDisplayMedia gets exposed when registerGlobals is called.

getDisplayMedia api improvements

---

android/src/main/java/com/oney/WebRTCModule/WebRTCView.java

We haven't supported API level < 18 for a long time.

android: remove no longer needed compatibility code

---

android/src/main/java/com/oney/WebRTCModule/WebRTCView.java

Paetially reverts:
https://github.com/react-native-webrtc/react-native-webrtc/commit/cec18d23448fc3a96605838d11b8030074643e06
I was wrong about removeSink, it may throw because we are running
operations on different threads and are neck-deep in thread-safety
territory. If videoTrack.dispose() is running while we try to call
removeSink(), it will crash.
Fixes:
https://github.com/react-native-webrtc/react-native-webrtc/issues/1077

android: fix chrash on removeSink

---

android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java

Problem: react-native-webrtc library crashes with "Failed to create EGL context" exception even with single context because EGL context is not released properly on dispose. 
Investigation: I explored chromium library and found this in there documented code at VideoCapturer.java
/*The caller still has ownership of {@code
* surfaceTextureHelper} and is responsible for making sure surfaceTextureHelper.dispose() is
* called. This also means that the caller can reuse the SurfaceTextureHelper to initialize a new
* VideoCapturer once the previous VideoCapturer has been disposed. */
It is further documented in SurfaceTextureHelper.java:
/**
* Helper class for using a SurfaceTexture to create WebRTC VideoFrames. In order to create WebRTC
* VideoFrames, render onto the SurfaceTexture. The frames …

fix "Failed to create EGL context" exception

---

package-lock.json
package.json
src/MediaStream.js
src/RTCUtil.js

Started getting this warning recently.
warning react-native-webrtc > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Should be a simple non-disruptive upgrade.

android: update uuid to get rid of the warning

---

README.md

In lieu of this PR https://github.com/react-native-webrtc/react-native-webrtc/pull/1013 we created the [out of tree plugin](https://github.com/expo/config-plugins/tree/master/packages/react-native-webrtc) to get users going faster, this PR updates the Expo notice to redirect users to the external plugin until we can land the upstream (versioned) plugin.

Added improved notice for Expo users

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule.m
package-lock.json
package.json
tools/build-webrtc.py

NOTE: this build uses dsSCTP instead of usrsctp for data channels, any feedback while testing them is welcome.

android,ios: update WebRTC to M98

---

android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
android/src/main/java/com/oney/WebRTCModule/VideoTrackAdapter.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
ios/RCTWebRTC/WebRTCModule+VideoTrackAdapter.h
ios/RCTWebRTC/WebRTCModule+VideoTrackAdapter.m
src/MediaStreamTrack.js
src/RTCPeerConnection.js

Don't use the stream ID as an identifier, just the track ID will do
since we have the PC ID already and this is only applied to remote
tracks.
In addition make the `muted` property readonly (as per the spec) and
also don't set it when `enabled` is set.

android,ios: refactor remote mute detection

---

README.md

The version of webrtc is now 100 not 94.

Update README webrtc version

---

ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

Until now numeric values had been treated the same as strings so they were serialized with double quotes around them, leading to the wrong data type (string instead of number) on the JS side. This adds the correct handling for numeric values.
Examples from the `pc.getStats()` results (see e.g. the `packetsSent` and `bytesSent` values):
**before fix**
```
"RTCOutboundRTPAudioStream_627959139": {
"timestamp": 1651482998659.26,
"type": "outbound-rtp",
"id": "RTCOutboundRTPAudioStream_627959139",
"codecId": "RTCCodec_audio_Outbound_111",
"mediaType": "audio",
"trackId": "RTCMediaStreamTrack_sender_1",
"remoteId": "RTCRemoteInboundRtpAudioStream_627959139",
"packetsSent": "1439",
"transportId": "RTCTransport_audio_1",
"retransmittedPacketsSent": "0",
"headerBytesSent": "28780",
"ssrc": …
```

ios: fix generated JSON for numeric stats values

---

src/MediaStream.ts
src/MediaStreamTrack.ts
src/RTCDataChannel.ts
src/RTCPeerConnection.ts
src/RTCSessionDescription.ts
src/RTCUtil.ts
src/getDisplayMedia.ts
src/getUserMedia.ts
src/index.ts

The current version of the repo has numerous type issues that make `react-native-webrtc` rather difficult to use in a TypeScript project. I've added explicit return types to numerous functions (as they were resolving to `unknown` or `any` on any external project that used `react-native-webrtc`), as well cleaned up several other minor aspects of the code base.
There are other changes that need to be made, but this pull request primarily focuses on the return types and a few other miscellaneous changes.

Cleanup Type Issues

---

android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
android/src/main/java/com/oney/WebRTCModule/videoEffects/ProcessorProvider.java
android/src/main/java/com/oney/WebRTCModule/videoEffects/VideoEffectProcessor.java
android/src/main/java/com/oney/WebRTCModule/videoEffects/VideoFrameProcessor.java
android/src/main/java/com/oney/WebRTCModule/videoEffects/VideoFrameProcessorFactoryInterface.java
src/MediaStreamTrack.ts

this is the video effect registry
to create a video effect you have to implement VideoFrameProcessorFactoryInterface
for example :
`
import org.webrtc.*;
import com.oney.WebRTCModule.videoEffect.VideoFrameProcessor;
import com.oney.WebRTCModule.videoEffect.VideoFrameProcessorFactoryInterface;
public class Rotate90Factory implements VideoFrameProcessorFactoryInterface {
public VideoFrameProcessor build() {
return new VideoFrameProcessor() {
@Override
public VideoFrame process(VideoFrame frame, SurfaceTextureHelper textureHelper) {
return new VideoFrame(frame.getBuffer().toI420(), 0, frame.getTimestampNs());
}
};
}
}`
then you have to add this processor in processor map 
`
import com.oney.WebRTCModule.videoEffect.ProcessorMap;
@ReactMethod
public void addMethods() {
Rotate90Factory rotate90 …

video effect registry done

---

android/src/main/java/com/oney/WebRTCModule/SerializeUtils.java
ios/RCTWebRTC/SerializeUtils.m
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
ios/RCTWebRTC/WebRTCModule+Transceivers.m
src/RTCRtpEncodingParameters.ts
src/RTCRtpSendParameters.ts

Android is tested and working but unsure about iOS as of yet 😄 
Including the following on the init array for a sending Transceiver seems to give the correct `SDP offer`.
```
sendEncodings: [
{
rid: 'h',
maxBitrate: 1200 * 1024
},
{
rid: 'm',
maxBitrate: 600 * 1024,
scaleResolutionDownBy: 2
},
{
rid: 'l',
maxBitrate: 300 * 1024,
scaleResolutionDownBy: 4
}
]
```
The resulting `SDP` now includes the following.
```
a=rid:h send
a=rid:m send
a=rid:l send
a=simulcast:send h;m;l
```
I haven't gone as far as to actually test if simulcasting actually works or needs extra implementation.

sendEncodings support

---

src/RTCPeerConnection.ts
src/index.ts

See issue: https://github.com/react-native-webrtc/react-native-webrtc/issues/1197
This PR updates the signature of RTCPeerConnection.addTrack() to allow a rest parameter for the second argument, accepting one or more `MediaStream`s rather than an array of `MediaStream`s.
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTrack
Additionally, this PR updates `registerGlobals()` to expose the `MediaStreamTrackEvent` interface in the global context. This should improve compatibility with libraries like [SIP.js](https://github.com/onsip/SIP.js) which expect this interface to be available globally (example usage [here](https://github.com/onsip/SIP.js/blob/main/src/platform/web/session-description-handler/session-description-handler.ts#L181)). …

Fix RTCPeerConnection.addTrack signature

---

src/RTCPeerConnection.ts

This PR changes the peerConnectionOnRemoveTrack listener to read the correct id value.

fix incorrect parameter name

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+Transceivers.m
src/RTCRtpSender.ts

On Android it was declared as a synchronous method, but it returns a promise.
On iOS the promise was never resolved.
Also rewrite the JS part to use async / await.

sender: fix setParameters

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
ios/RCTWebRTC/WebRTCModule+Transceivers.m
ios/RCTWebRTC/WebRTCModule.h
ios/RCTWebRTC/WebRTCModule.m
src/RTCPeerConnection.ts
src/RTCRtpTransceiver.ts

Setting the direction and stopping are asynchronous operations, so we can use a promise under the hood to simplify error handling.

transceivers: simplify error handling

---

src/MediaStreamTrack.ts
src/RTCPeerConnection.ts

- Emit unmute in ontrack
- Emit mute when a remote track is removed
- Add helper function to encapsulate setting the state ane emitting the event

pc,track: refactor emitting (un)mute events for remote tracks

---

ios/RCTWebRTC/SerializeUtils.m

iOS: Fix MediaStreamTrack readyState always ended

---

ios/RCTWebRTC/RCTConvert+WebRTC.m
src/RTCIceCandidate.ts
src/RTCPeerConnection.ts

Do `addIceCandidate` without `sdpMid` will crash on [this line](https://webrtc.googlesource.com/src/+/refs/heads/main/sdk/objc/api/peerconnection/RTCIceCandidate.mm#65)
In [spec](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/sdpMid) it must not null

ios: ensure property not null to prevent crash

---

android/src/main/java/com/oney/WebRTCModule/WebRTCView.java

Make sure add/removeSink operations run in the WebRTC thread, so it's safe to dispose and not get an error when concurrently modifying the sinks container, which happens inside WebRTC.
Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1257

android: fix race condition when disposing tracks

---

ios/RCTWebRTC/RTCVideoViewManager.m

Clear iOS videoView by rendering a 1x1 blank frame before changing track

---

android/src/main/java/com/oney/WebRTCModule/CameraCaptureController.java

I created a run time crash on java by forgetting to remove the break statement with the for loop removal in #1277. 
Apologies.

fix: remove unncessary break statement

---

android/src/main/java/com/oney/WebRTCModule/CameraCaptureController.java

Fixes a var naming collision that was preventing the android build from completing.
Related to #1277 .

Fix (Android): Fix variable naming

---

android/src/main/java/com/oney/WebRTCModule/ScreenCaptureController.java

`ScreenCapturerAndroid` currently doesn't stop when the MediaProjection is stopped (only stops when `stopCapture` is called). This stops the capturer when that happens so we can release any resources associated with capture.

android: stop screen capture when media projection is stopped

---

android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC.xcodeproj/project.pbxproj
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.h
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m

Addresses #805. Exposes the needed methods to create a video track with a custom capturer.
Note: I was able to get Android working fine. iOS streamed video to remote subscribers fine, but when displaying that same video locally, it only displayed a solid color; not sure where the source of that issue lies.

Add ability to create local custom tracks

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
src/RTCPeerConnection.ts

Make sure we handle the async result and move to the WebRTC thread
before sending events to JS.
This also fixes some underlying timing issues: the SDP was not up to
date inside the `track` event, which may have created some subtle
shenanigans for some.
This should also fix some crashes we have been seeing when getting the
native transceiver list, since the operation will have been completed
by the time we get it again.
Ref: https://github.com/react-native-webrtc/react-native-webrtc/issues/1284
Ref: https://github.com/react-native-webrtc/react-native-webrtc/issues/1289

Refactor SDP operations

---

android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
src/RTCPeerConnection.ts

First trigger the PC close(), then wait until the connection state goes to "closed" and dispose it. This guarantees that all state change listeners and data channel events fire before teh actual closure.

pc: refactor PeerConnection close

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/SerializeUtils.m
src/RTCPeerConnection.ts
src/RTCRtpTransceiver.ts

sLD / sRD could trigger a transceiver to transition to the stopped state. Propagate that flag from native to JS.

transceiver: make sure the stopped flag is synced after sLD / sRD

---

ios/RCTWebRTC/WebRTCModule.m

Context: https://bugs.chromium.org/p/webrtc/issues/detail?id=10966
The default ICE network policy doesn't work with iPhones that have dual sims. There's a field trial to fix this that was created in 2020 but hasn't been turned on default yet. Seems like others have turned it on with no issues, and verified that this works in our project.
Not sure if this is the best way to handle this though; only one field trial dictionary is in effect at any time, so this would overwrite any user-defined field trials. Should this just be an iOS installation instruction instead?

Turn on NWPathMonitor field trial to fix dual sim connectivity

---

Documentation/BasicUsage.md
Documentation/CallGuide.md

As stream api was deprecated and replaced by tracks, I updated docs to correspond actual code. 
Also `RTCPeerConnection::createAnswer` don't have any params anymore, so removed this from docs as well.

Updated Basic Usage and Call Guide docs

---

src/RTCRtpTransceiver.ts
src/index.ts

Won't fix [this](https://github.com/react-native-webrtc/react-native-webrtc/issues/1346) issue but will make developers aware that they will need to run pod install or npm install as it would appear some linking commands don't always execute properly when adding packages to your project.
Not actually sure if that is intentional or not.
Also would it be worth mentioning anything about alternative package managers like yarn?

Quick null check for both ios and android.

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m
src/MediaStream.ts
src/MediaStreamTrack.ts

We generate random UUIs for our local tracks, but collisions are possible for remote tracks. The unicity of tracks IDs is guaranteed only in the scope of a single PeerConnection.
Thus, use the PeerConnection internal ID when we go looking for a track. For local tracks we'll use an ID of -1.
Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1347

streams: fix matching remote tracks

---

ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m

Not sure if we can get actual framerate used, but 30 should be a little more reasonable as a default dummy value.

ios: update dummy framerate value

---

Documentation/AndroidInstallation.md
android/build.gradle

We have already de-facto done it since some of the code after the migration to UP requires API level 24.

android: bump API level to 24, aka Android 7

---

android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m

We ignore them in the JS layer. It just defaults to ''.

gum: don't pass any track label

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
src/RTCPeerConnection.ts
src/RTCRtpTransceiver.ts

They may create new transceivers, so make sure we create the corresponding JS objects.
Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1353
Ref: https://github.com/react-native-webrtc/react-native-webrtc/pull/1375

pc: fix handling legacy options in createOffer

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/SerializeUtils.m
src/RTCPeerConnection.ts

We were inadvertently skipping transceivers with currentDirection set tu null, which will be the case for those which were added before sLD was called.
Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1404

pc: fix not updating transceivers in sLD

---

src/index.ts

Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1371

log: only enable the rn-webrtc logger automatically

---

android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
src/RTCPeerConnection.ts

This PR fixes getting `RTCPeerConnection.localDescription` and `RTCPeerConnection.remoteDescription` according to WebRTC docs:
> On a more fundamental level, the returned value is the value of [RTCPeerConnection.pendingLocalDescription](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/pendingLocalDescription) if that property isn't null; otherwise, the value of [RTCPeerConnection.currentLocalDescription](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/currentLocalDescription) is returned. See [Pending and current descriptions](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) in the WebRTC Connectivity page for details on this algorithm and why it's used.

Add pending and current descriptions

---

android/src/main/java/com/oney/WebRTCModule/SerializeUtils.java

Android is using `INACTIVE` rather than `SEND_RECV` as the default transceiver direction.
Simple change to resolve the issue and put things inline with iOS and [spec](https://www.w3.org/TR/webrtc/#dom-rtcrtptransceiverinit).
Closes #1441

Android, fix default transceiver direction

---

src/MediaStream.ts
src/MediaStreamTrackEvent.ts
src/MessageEvent.ts
src/RTCDataChannel.ts
src/RTCDataChannelEvent.ts
src/RTCErrorEvent.ts
src/RTCEvent.ts
src/RTCIceCandidateEvent.ts
src/RTCPeerConnection.ts
src/RTCTrackEvent.ts

Add type to most of event that from event-target-shimmer
- MediaStreamTrackEvent
- MessageEvent
- RTCIceCandidateEvent
- RTCTrackEvent

Add type to event in RTCPeerConnection and RTC DataChannel

---

src/MediaStream.ts
src/RTCIceCandidate.ts

The type of the constructor parameter is currently 
```
{  candidate?: string, sdpMLineIndex?: null, sdpMid?: null }
```
which causes TypeScript errors despite valid parameters like
```
new RTCIceCandidate({candidate: 'candidateString', sdpMLineIndex: 0, sdpMid: 'sdpMidString'});
```
This fix allows constructing the class without TypeScript issues.
As far as I can tell, shouldn't cause issues to any existing implementations.
EDIT:
Added typing for MediaStream constructor, too.

Improve typing of RTCIceCandidate and MediaStream

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
src/RTCPeerConnection.ts

It should usually only trigger for bugs in the library, but things will break in very weird ways otherwise.
Ref: https://github.com/react-native-webrtc/react-native-webrtc/issues/1453

pc: handle PC initialization failures

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

When WebRTCModule is initialized twice, app crashes.
To reproduce:
1. before WebRTCModule is initialized(such as `Application.onCreate()`), inject new `audioDeviceModule` created by `JavaAudioDeviceModule.builder` in `WebRTCModuleOptions.getInstance()`.
2. Apply Codepush update, which triggers React Context to be recreated.
3. WebRTCModule is initialized again, then it crashes when executing `createPeerConnectionFactory` (https://github.com/react-native-webrtc/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L97)
I think its because `nativeAudioDeviceModule` cannot be created twice.
If I release existing audio device module before executing `createPeerConnectionFactory`, the app does not crash.

fix(android): release JavaAudioDeviceModule via onCatalystInstanceDestroy method

---

src/RTCPeerConnection.ts

Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1498

dc: send open event after datachannel event

---

android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

Removes the old manually filtered getStats and uses the libwebrtc supported `getStats` methods for RtpReceiver and RtpSender.
Fixes #1513

android: use libwebrtc getStats for RtpReceiver and RtpSender

---

android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

Not sure if this was an intentional omission, but I noticed that a track is kept around after it has been removed from the peer connection. This was causing issues when the track with the same id was added back to the peer connection, as any calls on the track at the JS layer would be pointed at the stale track. Are there any issues with removing the track here?

android, ios: remove track when removed from peerconnection

---

android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

Browsers don't seem to fail for `getStats()` on closed peer connections/senders/receivers (and the spec doesn't seem to allow for rejecting it). For RTCRtpSender/Receivers, they return an empty stats report, while there's a lone entry for peer connections:
```
{
"id": "P",
"timestamp": 1712746990577.823,
"type": "peer-connection",
"dataChannelsClosed": 0,
"dataChannelsOpened": 2
}
```
To closer align with the spec, this PR just has them all return empty maps if the native equivalent can't be found.

android,ios: don't reject promise for getStats when peer connection doesn't exist

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/RCTConvert+WebRTC.m
src/RTCIceCandidate.ts
src/RTCPeerConnection.ts

Fixes #1518 
I have tested this on Android, but not on iOS as I have no access to a mac.

Fix #1518 - Support null values in either sdpMid or sdpMLineIndex (but not both)

---

ios/RCTWebRTC/RTCVideoViewManager.m

The way the renderer is implemented is as follows: there is a UIView which holds on to a RTCMTLVideoView, which does the actual rendering in metal.
Rather than using our own home-grown mechanism to layout the views, just make sure the Metal view takes 100% of the space of our view, and then use the `videoContentMode` property to set it to cover or contain, matching the way a browser would do it.
This greatly simplifies the code because we lonnger care about the video size, the Metal renderer makes the adjustments autmagically.
In addition, the mirror and object-fit properties are only applied once, when they change, not on every layout change, which is unnecessary.

ios: refactor rendering in RTCVideoView

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

JavaAudioDeviceModule can be released after creating the PeerConnectionFactory, as per the sdk example:
https://webrtc.googlesource.com/src/+/4e86aa0870e5e34031a320e9ef95e86c897ffa4e/examples/androidapp/src/org/appspot/apprtc/PeerConnectionClient.java#456
Note that this only releases the native pointer and doesn't make the module itself inoperable.
This PR also fixes the behavior for RN 0.74+, as `onCatalystInstanceDestroy` (which was responsible for calling `release`) is no longer called there.

android: release audio device module after creating factory

---

examples/GumTestApp/ios/GumTestApp.xcodeproj/project.pbxproj
examples/GumTestApp/ios/Podfile

These were causing build errors recently, and were generally unneeded anyways.

ci: remove flipper from gumtestapp

---

android/src/main/java/com/oney/WebRTCModule/AbstractVideoCaptureController.java
android/src/main/java/com/oney/WebRTCModule/CameraCaptureController.java
android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
android/src/main/java/org/webrtc/Camera1Helper.java
android/src/main/java/org/webrtc/Camera2Helper.java

MediaStreamTrack.getSettings() should report the actual values rather than the target constraints; this PR grabs the size that the camera capturer will eventually resolve to.

android: report actual size in camera MediaStreamTrack settings

---

src/RTCPeerConnection.ts
src/RTCRtpParameters.ts
src/RTCRtpSendParameters.ts

It's possible for user code to replace encodings entirely. Thus, the resulting array will not have RTCRtpEncodingParameters object instances, but plain objects.
Handle it by deep-cloning the objects with JSON.parse(JSON.stringify(x)) since that will take care of appropriately serializing them, no matter the type.

sender: fix serializing RTCRtpSendParameters

---

Documentation/iOSInstallation.md
ios/RCTWebRTC.xcodeproj/project.pbxproj
ios/RCTWebRTC/WebRTCModule+RTCAudioSession.m
src/RTCAudioSession.ts
src/index.ts

Adds `audioSessionDidActivate` and `audioSessionDidDeactivate` methods for JS usage.
Incoming CallKit calls seem to hold the audio session in a restricted state, which won't let WebRTC activate it on its own (and gets interpreted as an error). These methods need to be called for smooth usage with CallKit.

ios: Add RTCAudioSession convenience methods needed for CallKit

---

Documentation/BasicUsage.md
android/src/main/java/com/oney/WebRTCModule/AbstractVideoCaptureController.java
android/src/main/java/com/oney/WebRTCModule/CameraCaptureController.java
android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
android/src/main/java/com/oney/WebRTCModule/ScreenCaptureController.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/CaptureController.h
ios/RCTWebRTC/CaptureController.m
ios/RCTWebRTC/ScreenCaptureController.m
ios/RCTWebRTC/VideoCaptureController.h
ios/RCTWebRTC/VideoCaptureController.m
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m
package.json
src/Constraints.ts
src/MediaDevices.ts
src/MediaStreamTrack.ts
src/getUserMedia.ts
src/index.ts

Adds [missing deviceId/groupId values](https://w3c.github.io/mediacapture-main/#media-track-settings) to the settings map sent back for MediaStreamTracks.
Additionally changes the `_switchCamera` method to an async method, so that it can get the final settings of the camera when done switching.
The one thing that's missing is iOS audio track deviceId/groupId. Can't find any way to associate the available input mics to the one actually in use by WebRTC. Can change `enumerateDevices` to send back a dummy deviceId like we do on Android, since iOS webrtc doesn't really do anything with audio device ids either, but I'm not sure if this might adversely affect anybody by this change.

ios,android: add device/groupId to MediaStreamTrack.getSettings and implement applyConstraints

---

android/build.gradle

Client apps could set their minSdkVersion to a lower version (RN 0.73 defaults to 21, and RN 0.74 is at 23), unknowingly sidestepping the minSdkVersion restriction.
They can still explicitly override it by adding the following to their app's AndroidManifest.xml:
```
<uses-sdk tools:overrideLibrary="com.oney.WebRTCModule"/>
```

android: don't use minSdkVersion set by app

---

Documentation/AndroidInstallation.md
android/build.gradle
android/consumer-rules.pro

Addresses #590 so that downstream consumers don't have to add their own rule (which can be annoying in Expo environments).
----
~~Needs testing. This works elsewhere for AARs, but I need to verify that it works in the react-native build system. Will get to it this weekish, but putting this up here for now.~~
Tested, works fine.

android: add libwebrtc consumer proguard rules

---

src/RTCPIPView.tsx

- This PR improves RTCPIPView component forwardRef type definition to remove @ts-ignore

Improve RTCPIPView component forwardRef type definition

---

android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java

As unlikely as it seems, we are observing this on Crashlytics:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
at com.oney.WebRTCModule.CameraCaptureController.createVideoCapturer(CameraCaptureController.java:103)
at com.oney.WebRTCModule.AbstractVideoCaptureController.initializeVideoCapturer(AbstractVideoCaptureController.java)
at com.oney.WebRTCModule.GetUserMediaImpl.createVideoTrack(GetUserMediaImpl.java)
at com.oney.WebRTCModule.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:197)
at com.oney.WebRTCModule.WebRTCModule.lambda$getUserMedia$11(WebRTCModule.java:777)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1 …
```

android: fix NPE in gUM

---

src/Permissions.ts

This PR fixes a typo in `Permissions.ts`.
- `_validatePermissionDescriptior` → `_validatePermissionDescriptor`

fix: typo in _validatePermissionDescriptor method name
