react-native-webrtc/react-native-webrtc

ios/RCTWebRTC/RTCVideoViewManager.m

Simple update to enable clipping on RTCView based on the suggestion from @oney

Enables shapes clipping for RTCViev

---

ios/RCTWebRTC/WebRTCModule.m

Also deref all objects just to be safe.

Clean up RTCDataChannel objects on RN bridge reloads

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

check object is null when get() from SparseArray, such as
* mPeerConnections
* mMediaStreams
* mMediaStreamTracks
* mDataChannels
if object is null, log without touch anything to prevent crash.

[android] prevent crash if object is null

---

RTCIceCandidateEvent.js
RTCPeerConnection.js

Send null icecandidate when gathering complete

---

RTCPeerConnection.js
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

I never implemented the Android code that will let us receive DataChannel messages in JS. Whoops. Here it is!

Native to JS plumbing for DataChannel on Android

---

RTCPeerConnection.js
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

See https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setConfiguration

Add support for RTCPeerConnection.setConfiguration()

---

MediaStreamTrack.js
ios/RCTWebRTC/WebRTCModule+RTCDataChannel.m
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m

merge from jitsi master

---

README.md

Hi,
I have another demo with good UI, can you consider to add it in README?
- Web app and signaling server: https://rewebrtc.herokuapp.com/
- React native app repository: https://github.com/thoqbk/rewebrtc

Update README.md: add another demo

---

README.md

Custom APIs Switch Camera function name was wrong

Fix Typo on Readme

---

Documentation/iOSInstallation.md
react-native-webrtc.podspec

ios: add podspec file

---

RTCView.js

Fix propTypes error on Android with rn >= 0.45

---

ISSUE_TEMPLATE.md

Asking the same quations over and over again gets tiresome quickly. Let's try to have people file better reports.
@zxcpoiu what do you think?
For reference: https://github.com/blog/2111-issue-and-pull-request-templates

misc: add issue template

---

android/src/main/AndroidManifest.xml
android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
android/src/main/java/com/oney/WebRTCModule/PermissionUtils.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

Do it dynamically, based on the target SDK version as specified by the
application.

android: use the new permissions system on  Android API >= 23

---

android/src/main/java/com/oney/WebRTCModule/EglUtils.java
android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
android/src/main/java/com/oney/WebRTCModule/WebRTCView.java

See the individual commit logs for details.

android: HW video acceleration + camera2

---

Documentation/AndroidInstallation.md

Added steps to update the graddle and build tools to support Java 8.

Updated Android Instructions for M67

---

README.md

They are not up to date and are source of useless bug reports.

doc: remove demos from README

---

README.md

`const i` cannot be modified inside the loop

---

Documentation/iOSInstallation.md

Doc: Replace libstdc++.tbd with libc++.tbd

---

README.md

To use callkit or connection service with your voip application.

Add react-native-callkeep link

---

README.md
android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m

- Add camera position in device list. Now we can get it in facing property. 
- Fix readme
- Add RTCView explication with props

Add camera position in facing property

---

RTCPeerConnection.js
RTCUtil.js
android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
android/src/main/java/com/oney/WebRTCModule/VideoCaptureController.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
getUserMedia.js
ios/RCTWebRTC/VideoCaptureController.m
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

This PR implements modern style constraints and the ability to customize the resolution and framerate. All feedback is welcome!

Modern constraints

---

RTCUtil.js

fix typo of STANDARD_OA_OPTIONS in RTCUtil.js

fix: typo of STANDARD_OA_OPTIONS in RTCUtil.js

---

README.md

https://github.com/react-native-webrtc/react-native-webrtc/blob/ba027527105cd5ffe64b7dd03d8782b8228df34d/ios/RCTWebRTC/WebRTCModule%2BRTCMediaStream.m#L127

iOS sourceInfo.facing is whether "front" or "environment"

---

android/src/main/java/com/oney/WebRTCModule/DisplayUtils.java
android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
android/src/main/java/com/oney/WebRTCModule/ScreenCaptureController.java

Fixes:
https://github.com/react-native-webrtc/react-native-webrtc/issues/973

android: fix detecting rotation when screen sharing

---

RTCDataChannel.js
RTCPeerConnection.js
android/src/main/java/com/oney/WebRTCModule/DataChannelWrapper.java
android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
android/src/main/java/com/oney/WebRTCModule/ThreadUtils.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
examples/GumTestApp/android/build.gradle
ios/RCTWebRTC.xcodeproj/project.pbxproj
ios/RCTWebRTC/DataChannelWrapper.h
ios/RCTWebRTC/DataChannelWrapper.m
ios/RCTWebRTC/WebRTCModule+RTCDataChannel.h
ios/RCTWebRTC/WebRTCModule+RTCDataChannel.m
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.h
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
ios/RCTWebRTC/WebRTCModule.m

Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/962

core: refactor datachannel creation

---

RTCDataChannel.js

I'm not sure but I believe this was missing, @saghul?

fix: missing refactor of data channel

---

ios/RCTWebRTC/WebRTCModule+RTCDataChannel.m

fix: crash on ios when receiving a message

---

README.md

related to https://github.com/react-native-webrtc/react-native-webrtc/issues/913#issuecomment-821888154

add note to readme about react-native-web-shim

---

ios/RCTWebRTC/VideoCaptureController.h
ios/RCTWebRTC/VideoCaptureController.m

Handle AV system pressure level updates received when using the app in multitasking on iPad devices

ios: handle av system pressure level updates

---

README.md

Code was previously updated.  Bringing documentation into line.

Update M94 reference in README.md

---

ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

A bug fix for removeTrack method

IOS removeTrack bugfix

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
ios/RCTWebRTC/WebRTCModule.h
ios/RCTWebRTC/WebRTCModule.m
src/RTCPeerConnection.ts

Matches the web API and we already implement addTrack as a blocking method.

pc: make removeTrack a blocking method

---

android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
src/RTCPeerConnection.ts

The ontrack event should fire for the same track for example when the sender switches the direction from sendrecv to recvonly and then back.
This would cause the recipient's direction to go from sendrecv to sendonly and back. The ontrack event is sent when the direction changes fron NOT *recv* to *recv*.
Closes: https://github.com/react-native-webrtc/react-native-webrtc/pull/1208

pc: fix ontrack not firing multiple times in certain situations

---

src/RTCView.ts

fix(typescript): fix type for rtc view

---

src/EventEmitter.ts
src/RTCDataChannel.ts

Alrighty, git can be a pain sometimes 😆 
Best to just get a new pr going most the time.
Round 2, should be all good 👍🏻

Migrate RTCDataChannel to the new event handling

---

android/src/main/java/com/oney/WebRTCModule/DataChannelWrapper.java
ios/RCTWebRTC/DataChannelWrapper.h
ios/RCTWebRTC/DataChannelWrapper.m
ios/RCTWebRTC/WebRTCModule+RTCDataChannel.m
ios/RCTWebRTC/WebRTCModule.h
ios/RCTWebRTC/WebRTCModule.m
src/EventEmitter.ts
src/RTCDataChannel.ts

Should be up to scratch but needs testing 👍🏻 
Follows on from [#1082](https://github.com/react-native-webrtc/react-native-webrtc/pull/1082)
**Edit:**
Needs a kick after #1246 #1249

api: RTCDataChannel buffer amount implementation

---

ios/RCTWebRTC/SerializeUtils.h
ios/RCTWebRTC/SerializeUtils.m
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

Need to do some testing to ensure everything is working as expected.

Bringing iOS transceiver init handling closer to Android

---

src/RTCPeerConnection.ts

Add MediaStream addtrack and removetrack events

---

android/src/main/java/com/oney/WebRTCModule/CameraCaptureController.java

Based on https://github.com/react-native-webrtc/react-native-webrtc/pull/1273#issuecomment-1374408494

fix(android): search camera device by id

---

.github/workflows/android_ci.yml
.github/workflows/ci.yml
.github/workflows/ios_ci.yml
examples/GumTestApp/android/build.gradle
examples/GumTestApp/android/gradle/wrapper/gradle-wrapper.properties
examples/GumTestApp/ios/GumTestApp.xcodeproj/project.pbxproj
examples/GumTestApp/ios/GumTestApp/Images.xcassets/AppIcon.appiconset/Contents.json
examples/GumTestApp/ios/Podfile
examples/GumTestApp/package.json

As a sanity test, I made some github actions to compile the GumTestApp (which includes compiling the main webrtc lib).

Native CI builds

---

src/RTCPeerConnection.ts

Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1292

pc: fix initializing sender when offerToReceive is used

---

ios/RCTWebRTC/RTCVideoViewManager.m

Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1306
(See the commit message details)

Fix Metal rendering 🤘

---

Documentation/AndroidInstallation.md

Add knowledge from Crash on Android 9 NoSuchMethodError on java/nio/FloatBuffer.position into AndroidInstallation.md

update android Faq with issue '#1310' info

---

android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1309

android,ios: fix matching remote streams in onTrack

---

src/RTCPeerConnection.ts

When setting an answer description they should be filtered out if stopped: https://w3c.github.io/webrtc-pc/#set-the-session-description (6, 12).

pc: filter out stopped transceivers

---

Documentation/BasicUsage.md
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m
src/MediaStreamTrack.ts

Allows for changing the volume on individual MediaStreamTracks.

android, ios: Expose setVolume for MediaStreamTrack

---

android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java

Closes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1354

android: default to the H.264 + software codecs factories

---

android/src/main/java/com/oney/WebRTCModule/ScreenCaptureController.java

~~~
"main" tid=1 Waiting
at jdk.internal.misc.Unsafe.park (Native method)
at java.util.concurrent.locks.LockSupport.park (LockSupport.java:194)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt (AbstractQueuedSynchronizer.java:885)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1039)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1345)
at java.util.concurrent.CountDownLatch.await (CountDownLatch.java:232)
at org.webrtc.ThreadUtils$2.run (ThreadUtils.java:1)
at org.webrtc.ThreadUtils.executeUninterruptibly (ThreadUtils.java:1)
at org.webrtc.ThreadUtils.awaitUninterruptibly (ThreadUtils.java:1)
at …

android: fix ANR when handling rotation changes

---

android/src/main/java/com/oney/WebRTCModule/WebRTCView.java

Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1391

android: fix ANR when attaching / detaching tracks

---

ios/RCTWebRTC/WebRTCModule.m
ios/RCTWebRTC/WebRTCModuleOptions.h
ios/RCTWebRTC/WebRTCModuleOptions.m

Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1369

ios: add ability to customize RTCAudioDevice

---

Documentation/AndroidInstallation.md
Documentation/BasicUsage.md
Documentation/BuildingWebRTC.md

I noticed some grammar errors and typos.

grammar errors and typos

---

android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
src/RTCPeerConnection.ts

This reverts commit c3effb3a9caa0ac2a3ff33ba8cb08959e63692be.

Revert "pc,api: add pending and current descriptions"

---

src/RTCPeerConnection.ts

- Make sure the `urls` property is used, while supporting the deprecated `url`.
- Make sure all servers are lower-case since the C++ layer does a case insensitive parse.
Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1476

pc: sanitize ICE servers

---

android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java
android/src/main/java/com/oney/WebRTCModule/UVCCamera2Enumerator.java

Ref: https://github.com/jiangdongguo/AndroidUSBCamera/pull/647

android: disable UVC enumerator on Android 14

---

src/MediaDevices.ts
src/MediaStream.ts
src/MediaStreamTrack.ts
src/MediaStreamTrackEvent.ts
src/MessageEvent.ts
src/RTCDataChannel.ts
src/RTCDataChannelEvent.ts
src/RTCErrorEvent.ts
src/RTCIceCandidateEvent.ts
src/RTCPeerConnection.ts
src/RTCTrackEvent.ts

Quick pr, untested but will test shortly 👍🏻 
Hopefully Fixes https://github.com/react-native-webrtc/react-native-webrtc/issues/1503

Try and force the use of the correct event-target-shim module.

---

android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java

android: fix senderGetStats lookup

---

android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m

Reverts react-native-webrtc/react-native-webrtc#1525
Related Issue, Needs Investigating https://github.com/react-native-webrtc/react-native-webrtc/issues/1548

Revert "android, ios: remove track when removed from peerconnection"

---

ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m

ios: add all available camera device types

---

ios/RCTWebRTC/RTCVideoViewManager.m

Fixes: https://github.com/jitsi/jitsi-meet/issues/14441

ios: fix compatibility with RN >= 0.73

---

examples/GumTestApp/App.js
examples/GumTestApp/ios/GumTestApp/Info.plist
ios/RCTWebRTC/I420Converter.h
ios/RCTWebRTC/I420Converter.m
ios/RCTWebRTC/PIPController.h
ios/RCTWebRTC/PIPController.m
ios/RCTWebRTC/RTCVideoViewManager.h
ios/RCTWebRTC/RTCVideoViewManager.m
ios/RCTWebRTC/SampleBufferVideoCallView.h
ios/RCTWebRTC/SampleBufferVideoCallView.m
src/.eslintrc.cjs
src/RTCPIPView.tsx
src/RTCView.ts
src/index.ts
tsconfig.json

First draft of PIP on iOS. Suggestions on what the API should look like are appreciated.
Related issue: #1226
TODO:

ios: picture in picture implementation

---

Documentation/AndroidInstallation.md

This PR adds the manual for setting the audio category to media in Android

doc [Android] - set audio category to media

---

src/RTCUtil.ts

Fixes: https://github.com/react-native-webrtc/react-native-webrtc/issues/1742

pc: handle null when normalizing options
